### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by Bruce0203** [spigradle/spigradle#87]
```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)
        at kr.entree.spigradle.module.common.SubclassDetection.inspect(SubclassDetection.kt:103)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:45)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.execute(IncrementalTaskAction.java:26)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)

```

there is some issue related from embedded JVM platform, that reflections do not detect classes with Java 11.0.16...
[more info...](https://github.com/ronmamo/reflections/issues/440)

so I wish spigradle support using reflections option ON/OFF
[source code link](https://github.com/spigradle/spigradle/blob/master/src/main/kotlin/kr/entree/spigradle/module/common/SubclassDetection.kt#L103)

**Comment by Bruce0203** [comment]
I realized the problem was Java version compatibility problem...
Duh.
