### ISSUE TITLE
Spigradle downloads wrong plugin jar

### ISSUE THREAD

**Issue by HowanDev** [spigradle/spigradle#89]
I have stumbled upon a issue with protocollib, and potentially more plugins

This is the stripped build.gradle
```gradle
spigot {
    main = project.property("pluginMain")
    name = project.property("pluginName")
    apiVersion = project.property("pluginApiVersion")
    load = POSTWORLD
    authors = [project.property("pluginAuthors")]
    depends = [ "ProtocolLib" ]
    softDepends = [ ]
    loadBefore = [ ]
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url "https://repo.dmulloy2.net/repository/public/" }
}

dependencies {
    compileOnly 'org.jetbrains:annotations:24.0.1'
    compileOnly 'org.yaml:snakeyaml:2.0'
    compileOnly paper(project.property("mcVersion"))

    compileOnly 'com.comphenix.protocol:ProtocolLib:5.0.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.3'
    testImplementation 'org.assertj:assertj-core:3.24.2'
}
```

when running `preparePlugins` task, wrong version is downloaded and results in a 914 KB jar,
now if we go to [ProtocolLib spigot page](https://spigotmc.org/resources/protocollib.1997) we'll see that downloaded jar is 4.96 MB

If we use the slimmer jar an error will be thrown:

```java
[10:45:02 ERROR]: Error occurred while enabling Nexus v1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener
	at me.howandev.nexus.NexusPlugin.onEnable(NexusPlugin.java:69) ~[Nexus-1.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-43]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-43]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-43]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-43]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketListener
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 13 more
[10:45:02 INFO]: [Nexus] Disabling Nexus v1.0
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketListener
```

on the other hand, if the full jar is used (as expected) it works.
This issue was fixed in https://github.com/spigradle/spigradle/issues/42
though it seems to be back

**Comment by HowanDev** [comment]
nobody gives a shit, closed.

**Comment by HowanDev** [comment]
nobody gives a shit, closed.
