### ISSUE TITLE
org.gradle.api.plugins.Convention type has been deprecated

### ISSUE THREAD

**Issue by turikhay** [spigradle/spigradle#90]
This plugin may not work in Gradle 9.0 because [the concept of conventions is outdated](https://docs.gradle.org/8.2/userguide/upgrading_version_8.html#deprecated_access_to_conventions).

```
$ ./gradlew --warning-mode all --stacktrace

> Configure project :bungee
The org.gradle.api.plugins.Convention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2/userguide/upgrading_version_8.html#deprecated_access_to_conventions
        at org.gradle.internal.extensibility.DefaultConvention.logConventionDeprecation(DefaultConvention.java:398)
        at org.gradle.internal.extensibility.DefaultConvention.findPlugin(DefaultConvention.java:100)
        at org.gradle.internal.extensibility.DefaultConvention.getPlugin(DefaultConvention.java:89)
        at kr.entree.spigradle.module.common.SubclassDetection$Companion.register(SubclassDetection.kt:171)
        at kr.entree.spigradle.module.bungee.BungeePlugin.apply(BungeePlugin.kt:98)
        at kr.entree.spigradle.module.bungee.BungeePlugin.apply(BungeePlugin.kt:39)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:187)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:52)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:282)
...
```

**Comment by axelyhdez** [comment]
Did you get a solution?
I have the same error

**Comment by peienliudao** [comment]
I have the same problem.
how to resolve it?

**Comment by turikhay** [comment]
I consider this project abandoned. It hasn't gotten any commits for 2 years.
There are maintained alternatives that collectively provide parts of the functionality of this plugin:
- https://github.com/eldoriarpg/plugin-yml
- https://github.com/jpenilla/run-task
